#!/bin/bash
#SBATCH --partition=cpu
#SBATCH --time=02:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --job-name='QbC_preselect'
#SBATCH --account=pi_ozguryilmaze_umass_edu
#SBATCH --output=preselect_%j.out

module purge
module load conda/latest
conda activate /scratch/workspace/anshitagupta_umass_edu-ai-gold-confinement/conda_envs/flare_deal_env

DEAL_DIR="/scratch/workspace/anshitagupta_umass_edu-ai-gold-confinement/aravadikeshr_tests/au_workflow/pzc/DEAL"

python "${DEAL_DIR}/preselect_qbc.py" \
    --std_dev_file "${DEAL_DIR}/../MD/std_dev/MACE_Au_H2O_PZC_with_std_dev.xyz" \
    --outdir "${DEAL_DIR}" \
    --uncertainty_threshold 0.30 \
    --max_threshold_factor 3

echo "$(date)"
echo "Job finished"
