#!/bin/bash
#SBATCH --nodes=1              # Number of nodes
#SBATCH --ntasks-per-node=4    # Number of MPI ranks per node
#SBATCH --gres=gpu:4           # Number of requested gpus per node
#SBATCH --ntasks=4
#SBATCH --gpus-per-node=4
#SBATCH --cpus-per-task=8
#SBATCH --time 24:00:00        # Walltime, format: HH:MM:SS
#SBATCH --partition=gpu-preempt
#SBATCH --mem=64G
#SBATCH --job-name='train_NUM_MODEL'


# Source environment for Unity HPC
module purge
module load cuda/12.1
module load conda/latest
conda activate /scratch/workspace/anshitagupta_umass_edu-ai-gold-confinement/conda_envs/baseline_mace_env
export LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${LD_LIBRARY_PATH:-}"

# Dataset pre-processing (required for Multi-GPU training)
mkdir -p processed_data

python -m mace.cli.preprocess_data \
    --train_file="train_model_NUM_MODEL.xyz" \
    --valid_file="val_model_NUM_MODEL.xyz"\
	--energy_key='energy'\
	--forces_key='forces'\
    --atomic_numbers="[1, 8, 79]" \
    --r_max=6 \
    --h5_prefix="processed_data/" \
    --compute_statistics \
    --E0s="average" \
    --seed=558 \


# Training
echo $CUDA_VISIBLE_DEVICES
echo $SLURM_GPUS_ON_NODE
export CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES

srun python -m mace.cli.run_train \
    --name="MACE_Au_H2O_PZC_NUM_MODEL" \
    --train_file="./processed_data/train" \
	--valid_file="./processed_data/val" \
	--statistics_file="./processed_data/statistics.json" \
    --energy_key='energy'\
	--forces_key='forces'\
    --config_type_weights='{"Default":1.0}' \
    --model="MACE" \
    --r_max=6 \
    --max_L=0 \
	--num_channels=256 \
    --batch_size=4 \
    --max_num_epochs=800 \
    --valid_batch_size=4 \
    --patience=20 \
    --eval_interval=5 \
    --swa \
    --start_swa=640 \
    --ema \
    --ema_decay=0.99 \
    --amsgrad \
    --restart_latest \
    --device=cuda \
    --seed=SEED_NUMBER \
    --default_dtype="float32"\
	--distributed\
	--num_workers=8\
    --save_cpu
